---
- name: Retrieve Firmware Version from SLX Router
  hosts: slxrouter
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: slxos  # Adjust as necessary for your device.
  tasks:
    - name: Run show ver command
      ansible.netcommon.cli_command:
        command: "show ver"
      register: ver_output

    - name: Extract firmware version from show ver output
      set_fact:
        firmware_version: "{{ ver_output.stdout | regex_search('Firmware name:\\s*(\\S+)', '\\1') }}"
      
    - name: Print firmware version if found
      debug:
        msg: "Firmware version is: {{ firmware_version }}"
